# Generated by Django 6.0.1 on 2026-01-23 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='audios/')),
            ],
        ),
        migrations.CreateModel(
            name='NoiseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('text', models.TextField()),
                ('reverse_scale', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NoiseResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.noisequestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AudioEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annoyance', models.IntegerField(default=0)),
                ('eventfulness', models.IntegerField(default=0)),
                ('pleasantness', models.IntegerField(default=0)),
                ('traffic_noise', models.IntegerField(default=0)),
                ('other_noise', models.IntegerField(default=0)),
                ('human_sounds', models.IntegerField(default=0)),
                ('natural_sounds', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.audio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.userprofile')),
            ],
        ),
    ]
