# Generated by Django 6.0.1 on 2026-01-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioevaluation',
            name='calm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='audioevaluation',
            name='chaotic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='audioevaluation',
            name='monotonous',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='audioevaluation',
            name='uneventful',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='audioevaluation',
            name='vibrant',
            field=models.IntegerField(default=0),
        ),
    ]
