# Generated by Django 6.0.1 on 2026-02-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_audioevaluation_calm_audioevaluation_chaotic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
